language: rust
sudo: false
rust:
  - 1.24.1
  - stable
  - beta
  - nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - if [ "${MINIMAL_VERSIONS}" = "y" ]; then cargo update -Z minimal-versions; fi
  - cargo run -p ci
  - cargo run --example default
after_success:
  - travis-cargo --only nightly doc-upload

matrix:
  include:
    - rust: nightly
      env: MINIMAL_VERSIONS=y

notifications:
  email:
on_success: never
